# [START app_yaml]
runtime: nodejs24
instance_class: F1
handlers:
  # Serve all static files from the build folder
  - url: /static
    static_dir: build/static

  # Serve other static assets
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|svg|ico|json))
    static_files: build/\1
    upload: build/.*\.(js|css|png|jpg|jpeg|gif|svg|ico|json)

  # Let React Router handle all other routes
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
# [END app_yaml]
